apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: sa-impersonation-group
spec:
  forProvider:
    member: "group:devops@example.com"  # A Google group
    role: "roles/iam.serviceAccountUser"  # Allows impersonation
    serviceAccountIdSelector:
      matchLabels:
        example.com/name: my-service-account