apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: test-rotate-sa-keys
spec:
  forProvider:
    createIgnoreAlreadyExists: true
    description: sa for testing key rotation
    disabled: false
    displayName: Test Rotate SA keys
    project: axial-life-395119