apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: sa-impersonation-user
spec:
  forProvider:
    member: "user:jane.doe@example.com"  # A specific user
    role: "roles/iam.serviceAccountUser"  # Allows impersonation
    serviceAccountIdSelector:
      matchLabels:
        example.com/name: my-service-account